-- Insert Categories with UUIDs
INSERT INTO "Category" (id, name, slug) VALUES
  ('Automation', 'automation'),
  ('Data Processing', 'data-processing'),
  ('Email Marketing', 'email-marketing'),
  ('Social Media', 'social-media'),
  ('E-commerce', 'e-commerce'),
  ('CRM', 'crm'),
  ('Analytics', 'analytics'),
  ('Webhooks', 'webhooks'),
  ('API Integration', 'api-integration'),
  ('File Management', 'file-management'),
  ('Notifications', 'notifications'),
  ('Database', 'database'),
  ('Monitoring', 'monitoring'),
  ('Security', 'security'),
  ('Content Management', 'content-management'),
  ('Lead Generation', 'lead-generation'),
  ('Project Management', 'project-management'),
  ('Reporting', 'reporting'),
  ('Backup & Sync', 'backup-sync'),
  ('Communication', 'communication');

-- Insert Tags
INSERT INTO "Tag" (name, slug) VALUES
  ('Beginner', 'beginner'),
  ('Advanced', 'advanced'),
  ('Expert', 'expert'),
  ('Free', 'free'),
  ('Premium', 'premium'),
  ('Popular', 'popular'),
  ('New', 'new'),
  ('Updated', 'updated'),
  ('Hot', 'hot'),
  ('Trending', 'trending'),
  ('Gmail', 'gmail'),
  ('Slack', 'slack'),
  ('Discord', 'discord'),
  ('Telegram', 'telegram'),
  ('WhatsApp', 'whatsapp'),
  ('Google Sheets', 'google-sheets'),
  ('Excel', 'excel'),
  ('Airtable', 'airtable'),
  ('Notion', 'notion'),
  ('Trello', 'trello'),
  ('Asana', 'asana'),
  ('Monday.com', 'monday'),
  ('Jira', 'jira'),
  ('GitHub', 'github'),
  ('GitLab', 'gitlab'),
  ('Shopify', 'shopify'),
  ('WooCommerce', 'woocommerce'),
  ('Stripe', 'stripe'),
  ('PayPal', 'paypal'),
  ('Facebook', 'facebook'),
  ('Instagram', 'instagram'),
  ('Twitter', 'twitter'),
  ('LinkedIn', 'linkedin'),
  ('YouTube', 'youtube'),
  ('TikTok', 'tiktok'),
  ('Salesforce', 'salesforce'),
  ('HubSpot', 'hubspot'),
  ('Mailchimp', 'mailchimp'),
  ('SendGrid', 'sendgrid'),
  ('Zapier', 'zapier'),
  ('IFTTT', 'ifttt'),
  ('AWS', 'aws'),
  ('Google Cloud', 'google-cloud'),
  ('Azure', 'azure'),
  ('Docker', 'docker'),
  ('Kubernetes', 'kubernetes'),
  ('MySQL', 'mysql'),
  ('PostgreSQL', 'postgresql'),
  ('MongoDB', 'mongodb'),
  ('Redis', 'redis'),
  ('REST API', 'rest-api'),
  ('GraphQL', 'graphql'),
  ('JSON', 'json'),
  ('XML', 'xml'),
  ('CSV', 'csv'),
  ('PDF', 'pdf'),
  ('Image Processing', 'image-processing'),
  ('Text Processing', 'text-processing'),
  ('AI/ML', 'ai-ml'),
  ('OpenAI', 'openai'),
  ('ChatGPT', 'chatgpt'),
  ('Scheduled', 'scheduled'),
  ('Real-time', 'real-time'),
  ('Batch Processing', 'batch-processing'),
  ('Error Handling', 'error-handling'),
  ('Testing', 'testing'),
  ('Debugging', 'debugging'),
  ('Performance', 'performance'),
  ('Scalable', 'scalable'),
  ('Low-code', 'low-code'),
  ('No-code', 'no-code'),
  ('Enterprise', 'enterprise'),
  ('Startup', 'startup'),
  ('SaaS', 'saas'),
  ('B2B', 'b2b'),
  ('B2C', 'b2c');
